version: '3'
dotenv: [.env]

vars:
  PACKAGE_IMPORT_NAME: hotel_reservation
  PYTHON_VERSION: 3.11
  ENVIRONMENT: dev

tasks:
  create-venv:
    desc: Create a virtual environment
    cmds:
      - uv venv -p {{.PYTHON_VERSION}} .venv
    silent: false

  auto-sync:
    desc: Sync dependencies based on the environment
    cmds:
      - if [ "{{.ENVIRONMENT}}" = "dev" ]; then task sync-dev; fi
      - if [ "{{.ENVIRONMENT}}" = "test" ]; then task sync-test; fi

  sync-dev:
    desc: Sync project dependencies with optionals
    cmds:
      - uv sync --extra dev

  sync-test:
    desc: Sync only test dependencies
    cmds:
      - uv sync --extra test

  lint:
    desc: Run pre-commit hooks
    cmds:
      - uv run pre-commit run --all-files

  help:
    desc: Print all tasks defined in the Taskfile
    cmd: task -l
    silent: true

  sync-databricks:
    desc: Sync the cloned repo from local machine to Databricks workspace
    cmd: pip install - e .pyproject.toml

  default:
    cmds:
      - task: help
    silent: true
